String Builder needs to be final,
says travis
/home/travis/build/khiekmann/attila-load-test/src/test/java/_development/ExecutorTest.java:44:
error: local variable aSB is accessed from within inner class; needs to
be declared final

aSB.append("B1 " + Thread.currentThread() + "\n" );

^